-- init-template.sql

-- Create the two databases
CREATE DATABASE IF NOT EXISTS wiki_db;
CREATE DATABASE IF NOT EXISTS tracker_db;

-- Create user and grant privileges
CREATE USER IF NOT EXISTS 'MYSQL_USERNAME_PLACEHOLDER'@'%' IDENTIFIED BY 'MYSQL_PASSWORD_PLACEHOLDER';
GRANT ALL PRIVILEGES ON wiki_db.* TO 'MYSQL_USERNAME_PLACEHOLDER'@'%';
GRANT ALL PRIVILEGES ON tracker_db.* TO 'MYSQL_USERNAME_PLACEHOLDER'@'%';

-- Apply changes
FLUSH PRIVILEGES;
