name: Docker Compose Build Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build wiki image
        run: |
          docker build -t wiki ./bergwerk-wiki

      # - name: Build api image
      #   run: |
      #     docker build -t api ./api

      - name: Build api image
        run: |
          docker build -t api ./bergwerk-socketio

      - name: Build db image
        run: |
          docker build -t db ./bergwerk-db

      - name: Build cron image
        run: |
          docker build -t cron ./bergwerk-cron
